import type { DataCategory } from "@/types/dataset"

export const dataCategories: DataCategory[] = [
  {
    id: "business",
    name: "Business & Finance",
    description: "Business metrics, financial data, and company information",
    columns: [
      { id: "company_name", name: "Company Name", type: "string" },
      { id: "industry", name: "Industry", type: "string" },
      { id: "revenue", name: "Annual Revenue", type: "number" },
      { id: "employees", name: "Employee Count", type: "number" },
      { id: "founded", name: "Founded Year", type: "number" },
      { id: "country", name: "Country", type: "string" },
      { id: "ceo", name: "CEO", type: "string" },
      { id: "public", name: "Publicly Traded", type: "boolean" },
      { id: "stock_symbol", name: "Stock Symbol", type: "string" },
      { id: "market_cap", name: "Market Cap", type: "number" },
      { id: "profit_margin", name: "Profit Margin", type: "number" },
      { id: "growth_rate", name: "Growth Rate", type: "number" },
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce & Sales",
    description: "Product sales, customer data, and order information",
    columns: [
      { id: "order_id", name: "Order ID", type: "string" },
      { id: "product_name", name: "Product Name", type: "string" },
      { id: "category", name: "Category", type: "string" },
      { id: "price", name: "Price", type: "number" },
      { id: "quantity", name: "Quantity", type: "number" },
      { id: "customer_name", name: "Customer Name", type: "string" },
      { id: "customer_email", name: "Customer Email", type: "email" },
      { id: "date", name: "Order Date", type: "date" },
      { id: "payment_method", name: "Payment Method", type: "string" },
      { id: "shipping_cost", name: "Shipping Cost", type: "number" },
      { id: "discount", name: "Discount", type: "number" },
      { id: "status", name: "Order Status", type: "string" },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare & Medical",
    description: "Patient data, medical records, and healthcare metrics",
    columns: [
      { id: "patient_id", name: "Patient ID", type: "string" },
      { id: "age", name: "Age", type: "number" },
      { id: "gender", name: "Gender", type: "string" },
      { id: "blood_type", name: "Blood Type", type: "string" },
      { id: "condition", name: "Medical Condition", type: "string" },
      { id: "admission_date", name: "Admission Date", type: "date" },
      { id: "discharge_date", name: "Discharge Date", type: "date" },
      { id: "doctor", name: "Doctor", type: "string" },
      { id: "department", name: "Department", type: "string" },
      { id: "treatment", name: "Treatment", type: "string" },
      { id: "cost", name: "Treatment Cost", type: "number" },
      { id: "insurance", name: "Insurance Provider", type: "string" },
    ],
  },
  {
    id: "education",
    name: "Education & Academic",
    description: "Student records, course information, and academic metrics",
    columns: [
      { id: "student_id", name: "Student ID", type: "string" },
      { id: "student_name", name: "Student Name", type: "string" },
      { id: "age", name: "Age", type: "number" },
      { id: "grade", name: "Grade/Year", type: "string" },
      { id: "course", name: "Course", type: "string" },
      { id: "instructor", name: "Instructor", type: "string" },
      { id: "score", name: "Score/Grade", type: "string" },
      { id: "enrollment_date", name: "Enrollment Date", type: "date" },
      { id: "graduation_date", name: "Expected Graduation", type: "date" },
      { id: "major", name: "Major/Subject", type: "string" },
      { id: "gpa", name: "GPA", type: "number" },
      { id: "attendance", name: "Attendance Rate", type: "number" },
    ],
  },
  {
    id: "real_estate",
    name: "Real Estate & Property",
    description: "Property listings, sales data, and real estate metrics",
    columns: [
      { id: "property_id", name: "Property ID", type: "string" },
      { id: "address", name: "Address", type: "address" },
      { id: "city", name: "City", type: "string" },
      { id: "state", name: "State/Province", type: "string" },
      { id: "zip", name: "Zip/Postal Code", type: "string" },
      { id: "price", name: "Price", type: "number" },
      { id: "bedrooms", name: "Bedrooms", type: "number" },
      { id: "bathrooms", name: "Bathrooms", type: "number" },
      { id: "sq_ft", name: "Square Footage", type: "number" },
      { id: "year_built", name: "Year Built", type: "number" },
      { id: "property_type", name: "Property Type", type: "string" },
      { id: "listing_date", name: "Listing Date", type: "date" },
    ],
  },
  {
    id: "marketing",
    name: "Marketing & Advertising",
    description: "Campaign data, audience metrics, and marketing performance",
    columns: [
      { id: "campaign_id", name: "Campaign ID", type: "string" },
      { id: "campaign_name", name: "Campaign Name", type: "string" },
      { id: "channel", name: "Channel", type: "string" },
      { id: "start_date", name: "Start Date", type: "date" },
      { id: "end_date", name: "End Date", type: "date" },
      { id: "budget", name: "Budget", type: "number" },
      { id: "impressions", name: "Impressions", type: "number" },
      { id: "clicks", name: "Clicks", type: "number" },
      { id: "ctr", name: "CTR", type: "number" },
      { id: "conversions", name: "Conversions", type: "number" },
      { id: "cost_per_conversion", name: "Cost per Conversion", type: "number" },
      { id: "roi", name: "ROI", type: "number" },
    ],
  },
  {
    id: "hr",
    name: "HR & Employment",
    description: "Employee records, job listings, and HR metrics",
    columns: [
      { id: "employee_id", name: "Employee ID", type: "string" },
      { id: "name", name: "Name", type: "string" },
      { id: "position", name: "Position", type: "string" },
      { id: "department", name: "Department", type: "string" },
      { id: "hire_date", name: "Hire Date", type: "date" },
      { id: "salary", name: "Salary", type: "number" },
      { id: "manager", name: "Manager", type: "string" },
      { id: "location", name: "Office Location", type: "string" },
      { id: "email", name: "Email", type: "email" },
      { id: "phone", name: "Phone", type: "phone" },
      { id: "performance", name: "Performance Rating", type: "number" },
      { id: "status", name: "Employment Status", type: "string" },
    ],
  },
  {
    id: "iot",
    name: "IoT & Sensor Data",
    description: "Device readings, sensor data, and IoT metrics",
    columns: [
      { id: "device_id", name: "Device ID", type: "string" },
      { id: "timestamp", name: "Timestamp", type: "date" },
      { id: "temperature", name: "Temperature", type: "number" },
      { id: "humidity", name: "Humidity", type: "number" },
      { id: "pressure", name: "Pressure", type: "number" },
      { id: "light", name: "Light Level", type: "number" },
      { id: "battery", name: "Battery Level", type: "number" },
      { id: "location", name: "Location", type: "string" },
      { id: "status", name: "Status", type: "string" },
      { id: "alert", name: "Alert", type: "boolean" },
      { id: "maintenance_due", name: "Maintenance Due", type: "boolean" },
      { id: "firmware_version", name: "Firmware Version", type: "string" },
    ],
  },
]
